// All page copy. Paper facts (authors, venues, results) follow the PDFs in /public/papers.

const ME = "Antonio Neto";

const papers = [
  {
    id: "dpdp",
    titleEn: "An Attention-Based Approach to the Dynamic Pickup and Delivery Problem",
    titleOriginal: "Uma Abordagem Baseada em Atenção para o Problema de Coletas e Entregas Dinâmicas",
    authors: ["Antonio Neto", "Rodrigo Drummond Macedo", "Arley Henrique Duque", "Sandro Jerônimo de Almeida"],
    me: 0,
    venue: "LVIII SBPO (Brazilian Symposium on Operations Research)",
    year: 2026,
    status: "accepted",
    pdf: "/papers/neto-2026-sbpo-dpdp-attention.pdf",
    result: {
      en: "An attention model trained with reinforcement learning and combined with VNS local search. On the ICAPS 2021 benchmark, average cost is 16.3% below Tabu Search (global average over instance groups 1–64).",
      zh: "基于强化学习训练的注意力模型，并结合变邻域搜索（VNS）进行局部搜索。在 ICAPS 2021 基准上，全部算例组（1–64）的平均成本比禁忌搜索低 16.3%。",
      pt: "Modelo de atenção treinado com aprendizado por reforço e combinado com busca local VNS. No benchmark ICAPS 2021, custo médio 16,3% abaixo da Busca Tabu (média global dos grupos 1–64).",
    },
  },
  {
    id: "ga",
    titleEn: "Optimization of Bulk Carrier Loading and Unloading Operation Sequencing with Trim Constraints Using a Genetic Algorithm",
    titleOriginal: "Otimização do Sequenciamento de Operações de Carregamento e Descarregamento de Navios Graneleiros com Restrição de Trim via Algoritmo Genético",
    authors: ["Antonio Neto", "Rodrigo Drummond Macedo", "Carolina S. Almeida", "Claudio Roberto Xavier", "Tereza Cristina Vieira dos Santos", "Marcelo Rocha Cardozo", "Osmar Selhorst Filho", "Mariana Coelho de Frias", "Maycon Douglas Fernandes Lira", "Sandro Jerônimo de Almeida"],
    me: 0,
    venue: "LVIII SBPO (Brazilian Symposium on Operations Research)",
    year: 2026,
    status: "accepted",
    pdf: "/papers/neto-2026-sbpo-bulk-carrier-ga.pdf",
    result: {
      en: "On 112 real operational plans from the logistics operator VLI, trim-reference compliance rose from 29.12% to 84.80% and average operation time fell by 3.03%.",
      zh: "在物流企业 VLI 的 112 份真实作业计划上，纵倾达标率由 29.12% 提高到 84.80%，平均作业时间缩短 3.03%。",
      pt: "Em 112 planos operacionais reais da VLI, a conformidade de trim subiu de 29,12% para 84,80% e a duração média da operação caiu 3,03%.",
    },
  },
  {
    id: "drone",
    titleEn: "Multi-Period Drone Routing with Time Windows and Gradual Deployment of Charging Stations",
    titleOriginal: "Roteamento Multi-Período de Drones com Janelas de Tempo e Disponibilização Gradual de Estações de Recarga",
    authors: ["Antonio S. C. Neto", "Zenilton K. G. do Patrocínio"],
    me: 0,
    venue: "XXXIII SIMPEP (Brazilian Symposium on Production Engineering)",
    year: 2026,
    status: "accepted",
    pdf: "/papers/neto-2026-simpep-drone-routing.pdf",
    code: "https://github.com/nietus/tcc",
    result: {
      en: "Undergraduate thesis. MP-EAVNS is an energy-aware Variable Neighborhood Search for a multi-period E-VRPTW. Over 9,936 runs on 92 benchmark instances, every solution was feasible with all stations available (98.6% under gradual deployment), and routes were 6.7% shorter than an adapted ALNS.",
      zh: "本科毕业论文。提出能量感知的变邻域搜索算法 MP-EAVNS，求解带时间窗的多周期电动车辆路径问题（E-VRPTW）：在 92 个 E-VRPTW 基准算例上共运行 9,936 次，充电站全部可用时可行解比例为 100%，逐步部署时为 98.6%；充电站全部可用时，路径长度比改进的 ALNS 算法短 6.7%。",
      pt: "TCC. MP-EAVNS, uma Busca em Vizinhança Variável sensível à energia para um E-VRPTW multi-período: 9.936 execuções em 92 instâncias do benchmark E-VRPTW, 100% de viabilidade com todas as estações e 98,6% com disponibilização gradual; com todas as estações, rotas 6,7% mais curtas que a ALNS adaptada.",
    },
  },
  {
    id: "deepfactory",
    titleEn: "DeepFactory: A Multi-Agent System for Industrial Production Management and Optimization",
    titleOriginal: "DeepFactory: Sistema Multiagentes para Gestão e Otimização de Produção Industrial",
    authors: ["Rodrigo Drummond Macedo", "Antônio Neto", "Arley Henrique Duque", "Sandro Jerônimo de Almeida"],
    me: 1,
    venue: "LVIII SBPO (Brazilian Symposium on Operations Research)",
    year: 2026,
    status: "accepted",
    pdf: "/papers/macedo-neto-2026-sbpo-deepfactory.pdf",
    result: {
      en: "A prototype multi-agent platform that integrates material planning, MIP-based scheduling, predictive maintenance and computer-vision quality inspection, illustrated on a simulated pharmaceutical manufacturing scenario.",
      zh: "多智能体平台原型，集成物料计划、基于混合整数规划的生产排程、预测性维护和计算机视觉质量检测，并以模拟的制药生产场景作为示例。",
      pt: "Protótipo de plataforma multiagente que integra planejamento de materiais, sequenciamento por programação inteira mista, manutenção preditiva e inspeção por visão computacional, ilustrada em um cenário simulado de manufatura farmacêutica.",
    },
  },
  {
    id: "llm",
    titleEn: "An LLM-Based Multi-Agent System Integrated into Ship Loading and Unloading Management and Optimization Software",
    titleOriginal: "Proposta de um Sistema Multiagentes baseado em LLM: Integração em um Software de Gerenciamento e Otimização de Carregamento e Descarregamento de Navios",
    authors: ["Antonio S. Neto", "Rodrigo D. Macedo", "Carolina S. Almeida", "Arley Henrique Duque", "Sandro Jerônimo de Almeida"],
    me: 0,
    venue: "SBAI-SBSE (Brazilian Symposium on Intelligent Automation)",
    year: 2025,
    status: "published",
    pdf: "/papers/neto-2025-sbai-llm-multi-agent.pdf",
    result: {
      en: "Four specialised LLM agents (Manager, Helper, Optimizer and Data Analytics) integrated into conventional ship-operation software to register ships, generate optimized plans and build visual analyses.",
      zh: "将四个专用的大语言模型智能体（Manager、Helper、Optimizer、Data Analytics）集成到传统的船舶装卸管理软件中，用于登记船舶、生成优化方案并制作可视化分析。",
      pt: "Quatro agentes LLM especializados (Manager, Helper, Optimizer e Data Analytics) integrados a um software convencional de operação de navios para cadastrar navios, gerar planos otimizados e criar análises visuais.",
    },
  },
];

const text = {
  en: {
    htmlLang: "en",
    languageLabel: "Language",
    sectionsLabel: "Page sections",
    skipLabel: "Skip to content",
    name: ME,
    headline: "Final-year Computer Science undergraduate, PUC Minas, Brazil",
    tagline: "Combinatorial optimization · reinforcement learning · multi-agent systems",
    cv: "CV (PDF)",
    cvHref: "/Antonio_Neto_Curriculum.pdf",
    emailLabel: "E-mail",
    aboutTitle: "About",
    about: [
      "I am a final-year Computer Science undergraduate at PUC Minas, Brazil, graduating in December 2026, and an AI engineer at Deeptera.",
      "I have five peer-reviewed papers at the Brazilian conferences SBPO, SIMPEP and SBAI, four as first author. They cover metaheuristics for routing and scheduling, reinforcement learning for dynamic pickup and delivery, and LLM-based multi-agent systems for industrial software.",
    ],
    interestsTitle: "Research interests",
    interests: ["Combinatorial optimization", "Metaheuristics (genetic algorithms, VNS)", "Learning to optimize and reinforcement learning for routing", "LLM-based multi-agent systems for industrial decision support"],
    pubsTitle: "Publications",
    pubsNote: "Peer-reviewed papers at Brazilian national conferences. The PDFs are the authors' versions and are written in Portuguese; each entry gives an English title and summary.",
    statusLabel: { accepted: "Accepted", published: "Published" },
    pdfLabel: "PDF (author's version, in Portuguese)",
    codeLabel: "Code",
    originalLabel: "Original title",
    educationTitle: "Education",
    education: [
      { what: "B.Sc. in Computer Science, Pontifical Catholic University of Minas Gerais (PUC Minas), Brazil", when: "2023 – Dec 2026 (expected)", detail: "Thesis: multi-period drone routing with time windows and gradual deployment of charging stations, advised by Prof. Zenilton K. G. do Patrocínio. Selected grades (out of 100, pass mark 60): Thesis Project I 98, Design and Analysis of Algorithms 88, Artificial Intelligence 82, Graph Theory and Computability 80." },
      { what: "Mandarin, Confucius Institute at UFMG", when: "2024 – present", detail: "Currently at HSK 4 level." },
    ],
    experienceTitle: "Experience",
    experience: [
      { what: "Artificial Intelligence Engineer, Deeptera", when: "Apr 2026 – present", detail: "Part-time R&D on optimization and multi-agent systems. This work and my thesis led to four papers accepted at SBPO and SIMPEP 2026." },
      { what: "Computing and Data Intern, Deeptera", when: "Aug 2024 – Apr 2026", detail: "Genetic-algorithm optimization and backend services for the logistics operator VLI; first author of an LLM multi-agent paper published at SBAI-SBSE 2025." },
    ],
    projectsTitle: "Selected projects",
    projects: [
      { title: "Drone routing (thesis code)", href: "https://github.com/nietus/tcc", detail: "Reproducible GRASP/VNS experiments for multi-period drone routing on E-VRPTW benchmark instances." },
      { title: "Anki MCP", href: "https://github.com/nietus/anki-mcp", detail: "An MCP server that lets AI assistants create and review Anki flashcards; I use it for my Mandarin study." },
    ],
    skillsTitle: "Skills and languages",
    skills: [
      "Programming languages: Python, C, TypeScript",
      "Agent systems: LangChain, LangGraph, RAG, MCP",
      "Machine learning: PyTorch, scikit-learn",
      "Data science: Pandas, NumPy and data visualization",
      "Backend: Django, FastAPI, REST APIs",
      "Databases: PostgreSQL, MySQL",
      "DevOps: Azure DevOps, Docker",
      "Version control: Git, GitHub",
      "Optimization: Mathematical modeling, solvers and metaheuristics",
      "Cloud: Azure, Google Cloud",
      "Languages: Portuguese (native), English (fluent), Mandarin (HSK 4)",
    ],
    contactTitle: "Contact",
    footer: "Last updated October 2026",
  },
  zh: {
    htmlLang: "zh-CN",
    languageLabel: "语言",
    sectionsLabel: "页面章节",
    skipLabel: "跳至正文",
    name: ME,
    headline: "巴西米纳斯吉拉斯天主教大学（PUC Minas）计算机科学专业本科四年级学生",
    tagline: "组合优化 · 强化学习 · 多智能体系统",
    cv: "简历（PDF，英文）",
    cvHref: "/Antonio_Neto_Curriculum.pdf",
    emailLabel: "邮箱",
    aboutTitle: "个人简介",
    about: [
      "我是巴西米纳斯吉拉斯天主教大学（PUC Minas）计算机科学专业的本科四年级学生，将于 2026 年 12 月毕业，同时在 Deeptera 公司担任人工智能工程师。",
      "我在巴西全国性学术会议 SBPO（巴西运筹学研讨会）、SIMPEP（巴西生产工程研讨会）和 SBAI（巴西智能自动化研讨会）上发表或被录用了五篇经同行评审的论文，其中四篇为第一作者，内容包括路径优化与调度问题的元启发式算法、动态取送货问题的强化学习方法，以及面向工业软件的大语言模型多智能体系统。",
      "我在米纳斯吉拉斯联邦大学（UFMG）孔子学院学习中文，目前中文水平约为 HSK 四级。本页中文内容借助翻译工具完成，如有不当之处，敬请谅解。",
    ],
    interestsTitle: "研究兴趣",
    interests: ["组合优化", "元启发式算法（遗传算法、变邻域搜索）", "学习优化（learning to optimize）与面向路径问题的强化学习", "面向工业决策支持的大语言模型多智能体系统"],
    pubsTitle: "论文",
    pubsNote: "以下论文均发表或录用于巴西全国性学术会议，经同行评审。PDF 为作者版本，正文为葡萄牙语；每篇附英文标题和中文简介。",
    statusLabel: { accepted: "已录用", published: "已发表" },
    pdfLabel: "PDF（作者版本，葡萄牙语）",
    codeLabel: "代码",
    originalLabel: "原标题",
    educationTitle: "教育背景",
    education: [
      { what: "计算机科学专业本科（理学学士，在读），米纳斯吉拉斯天主教大学（PUC Minas），巴西", when: "2023 年 – 2026 年 12 月（预计）", detail: "毕业论文：带时间窗和充电站逐步部署的多周期无人机路径优化，指导教师为 Zenilton K. G. do Patrocínio 教授。部分课程成绩（满分 100 分，60 分及格）：毕业设计（一）98 分、算法设计与分析 88 分、人工智能 82 分、图论与可计算性 80 分。" },
      { what: "中文学习，米纳斯吉拉斯联邦大学（UFMG）孔子学院", when: "2024 年至今", detail: "目前中文水平约为 HSK 四级。" },
    ],
    experienceTitle: "工作经历",
    experience: [
      { what: "人工智能工程师，Deeptera", when: "2026 年 4 月至今", detail: "兼职从事优化问题和多智能体系统的研发；2026 年被 SBPO 和 SIMPEP 录用的四篇论文来自这项工作和我的毕业论文。" },
      { what: "计算与数据实习生，Deeptera", when: "2024 年 8 月 – 2026 年 4 月", detail: "为物流企业 VLI 开发基于遗传算法的优化方法和后端服务；以第一作者在 SBAI-SBSE 2025 发表大语言模型多智能体系统论文。" },
    ],
    projectsTitle: "项目",
    projects: [
      { title: "无人机路径优化（毕业论文代码）", href: "https://github.com/nietus/tcc", detail: "在 E-VRPTW 基准算例上进行多周期无人机路径优化的 GRASP/VNS 可复现实验。" },
      { title: "Anki MCP", href: "https://github.com/nietus/anki-mcp", detail: "一个 MCP 服务器，让 AI 助手可以创建和复习 Anki 记忆卡片；我用它来学习中文。" },
    ],
    skillsTitle: "技能与语言",
    skills: [
      "编程语言：Python、C、TypeScript",
      "智能体系统：LangChain、LangGraph、RAG、MCP",
      "机器学习：PyTorch、scikit-learn",
      "数据科学：Pandas、NumPy 与数据可视化",
      "后端开发：Django、FastAPI、REST API",
      "数据库：PostgreSQL、MySQL",
      "DevOps：Azure DevOps、Docker",
      "版本控制：Git、GitHub",
      "优化：数学建模、求解器与元启发式算法",
      "云平台：Azure、Google Cloud",
      "语言：葡萄牙语（母语）、英语（流利）、中文（HSK 4）",
    ],
    contactTitle: "联系方式",
    footer: "最后更新：2026 年 10 月",
  },
  pt: {
    htmlLang: "pt-BR",
    languageLabel: "Idioma",
    sectionsLabel: "Seções da página",
    skipLabel: "Ir para o conteúdo",
    name: ME,
    headline: "Estudante do último ano de Ciência da Computação, PUC Minas",
    tagline: "Otimização combinatória · aprendizado por reforço · sistemas multiagentes",
    cv: "Currículo (PDF)",
    cvHref: "/Antonio_Neto_CV_PT.pdf",
    emailLabel: "E-mail",
    aboutTitle: "Sobre",
    about: [
      "Sou estudante do último ano de Ciência da Computação na PUC Minas, com formatura em dezembro de 2026, e engenheiro de IA na Deeptera.",
      "Tenho cinco artigos revisados por pares nos eventos SBPO, SIMPEP e SBAI, quatro como primeiro autor, sobre metaheurísticas para roteamento e sequenciamento, aprendizado por reforço para coletas e entregas dinâmicas e sistemas multiagentes baseados em LLM para software industrial.",
    ],
    interestsTitle: "Interesses de pesquisa",
    interests: ["Otimização combinatória", "Metaheurísticas (algoritmos genéticos, VNS)", "Learning to optimize e aprendizado por reforço para roteamento", "Sistemas multiagentes baseados em LLM para apoio à decisão industrial"],
    pubsTitle: "Publicações",
    pubsNote: "Artigos revisados por pares em eventos nacionais. Os PDFs são as versões dos autores.",
    statusLabel: { accepted: "Aceito", published: "Publicado" },
    pdfLabel: "PDF (versão dos autores)",
    codeLabel: "Código",
    originalLabel: "Título em inglês",
    educationTitle: "Formação",
    education: [
      { what: "Bacharelado em Ciência da Computação, PUC Minas", when: "2023 – dez. 2026 (previsto)", detail: "TCC: roteamento multi-período de drones com janelas de tempo e disponibilização gradual de estações de recarga, orientado pelo Prof. Zenilton K. G. do Patrocínio. Notas selecionadas (de 100): TCC I 98, Projeto e Análise de Algoritmos 88, Inteligência Artificial 82, Teoria dos Grafos e Computabilidade 80." },
      { what: "Mandarim, Instituto Confúcio da UFMG", when: "2024 – atual", detail: "Nível HSK 4." },
    ],
    experienceTitle: "Experiência",
    experience: [
      { what: "Artificial Intelligence Engineer, Deeptera", when: "abr. 2026 – atual", detail: "P&D em meio período em problemas de otimização e sistemas multiagentes; quatro artigos aceitos no SBPO e no SIMPEP 2026 saíram desse trabalho e do meu TCC." },
      { what: "Estagiário em Computação e Dados, Deeptera", when: "ago. 2024 – abr. 2026", detail: "Otimização com algoritmos genéticos e serviços de backend para a VLI; primeiro autor de artigo sobre sistemas multiagentes com LLM publicado no SBAI-SBSE 2025." },
    ],
    projectsTitle: "Projetos selecionados",
    projects: [
      { title: "Roteamento de drones (código do TCC)", href: "https://github.com/nietus/tcc", detail: "Experimentos reprodutíveis de GRASP/VNS para roteamento multi-período de drones em instâncias E-VRPTW." },
      { title: "Anki MCP", href: "https://github.com/nietus/anki-mcp", detail: "Servidor MCP que permite a assistentes de IA criar e revisar flashcards do Anki; uso para estudar mandarim." },
    ],
    skillsTitle: "Habilidades e idiomas",
    skills: [
      "Linguagens de programação: Python, C, TypeScript",
      "Sistemas de agentes: LangChain, LangGraph, RAG, MCP",
      "Machine learning: PyTorch, scikit-learn",
      "Ciência de dados: Pandas, NumPy e visualização de dados",
      "Backend: Django, FastAPI, APIs REST",
      "Bancos de dados: PostgreSQL, MySQL",
      "DevOps: Azure DevOps, Docker",
      "Controle de versão: Git, GitHub",
      "Otimização: Modelagem matemática, solvers e metaheurísticas",
      "Cloud: Azure, Google Cloud",
      "Idiomas: português (nativo), inglês (fluente), mandarim (HSK 4)",
    ],
    contactTitle: "Contato",
    footer: "Atualizado em outubro de 2026",
  },
};

export { papers, text };
